# Generated by Django 5.2 on 2025-05-09 05:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(error_messages={'unique': 'این نام شرکت قبلاً ثبت شده است'}, help_text='نام رسمی شرکت یا سازمان (حداکثر 20 کاراکتر)', unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=20, message='نام شرکت نمی\u200cتواند بیش از 20 کاراکتر باشد')], verbose_name='نام شرکت')),
                ('phone_number', models.CharField(help_text='شماره تماس با فرمت ۰۹۱۲۳۴۵۶۷۸۹', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="شماره موبایل باید با '09' شروع شده و دقیقا 11 عدد باشد", regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('user', models.OneToOneField(help_text='حساب کاربری مرتبط بااین کارفرما', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سیستم')),
            ],
            options={
                'verbose_name': 'کارفرما',
                'verbose_name_plural': 'کارفرماها',
                'db_table': 'employers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='نام باید فقط شامل حروف فارسی و یک فاصله باشد.', regex='^[آ-ی\\s]+\\s+[آ-ی\\s]+$'), django.core.validators.MinLengthValidator(5)])),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="شماره موبایل باید با '09' شروع شده و دقیقا 11 عدد باشد.", regex='^09\\d{9}$')])),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('skill', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان پروژه نمی\u200cتواند خالی باشد', verbose_name='عنوان پروژه')),
                ('description', models.CharField(blank=True, help_text='توضیحات اختیاری درباره پروژه (حداکثر 255 کاراکتر)', max_length=255, null=True, verbose_name='توضیحات پروژه')),
                ('required_candidates', models.PositiveIntegerField(help_text='تعداد نیروی مورد نیاز برای پروژه (حداکثر 100 نفر)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='تعداد کارجو مورد نیاز')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='حقوق پیشنهادی به میلیون تومان', max_digits=10, verbose_name='حقوق پیشنهادی (معیار دلخواه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پروژه')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Recruitment.employer', verbose_name='کارفرما')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', verbose_name='وضعیت درخواست')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Recruitment.jobseeker', verbose_name='کارجو')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Recruitment.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
            },
        ),
        migrations.AddConstraint(
            model_name='employer',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_phone'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('required_candidates__lte', 100)), name='max_required_candidates'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job_seeker', 'project'), name='unique_application'),
        ),
    ]
