# Generated by Django 5.2 on 2025-05-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'verbose_name': 'کارجو', 'verbose_name_plural': 'کارجوها'},
        ),
    ]
