# Generated by Django 5.2 on 2025-05-14 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0002_alter_jobseeker_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='نام باید فقط شامل حروف فارسی و یک فاصله باشد.', regex='^[آ-ی\\s]+\\s+[آ-ی\\s]+$')], verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='نام باید فقط شامل حروف فارسی و یک فاصله باشد.', regex='^[آ-ی\\s]+\\s+[آ-ی\\s]+$'), django.core.validators.MinLengthValidator(5)], verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='معدل'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="شماره موبایل باید با '09' شروع شده و دقیقا 11 عدد باشد.", regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(help_text='حساب کاربری مرتبط بااین کارفرما', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سیستم'),
        ),
    ]
