# Generated by Django 5.2 on 2025-05-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0004_project_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='capacity',
        ),
    ]
